Add watcher tool
ethereum-optimism/optimism-monorepo pull request #371
Opened 2020-11-29 23:20 UTC by K-Ho

## Description

## Questions
- 
-
-

## Metadata
### Fixes
- Fixes # [Link to Issue]

## Contributing Agreement

- [ ] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

2020-12-01 20:12 UTC, tynes commented on packages/watcher/exec/run-watcher.js
> +			provider: l1Provider,
Tabs? Everything else is spaces

2020-12-01 20:12 UTC, tynes commented on packages/watcher/exec/run-watcher.js
> +
This needs env var parsing right?

2020-12-01 20:14 UTC, tynes commented on packages/watcher/src/watcher.ts
> +    // Message was relayed in the past
This might read a little better if unnested and multiple specific ifs
`if matches.length === 1`
`if matches.length > 1`

2020-12-01 20:18 UTC, tynes commented on packages/watcher/README.md
> +Our `Watcher` allows you to retrieve all transaction hashes related to cross domain messages such as deposits and withdrawals. In order to use, first send a transaction which sends a cross domain mes
I think replacing personal pronouns with words like `the` is better for docs. In this case, its `Our`, the first word

2020-12-01 20:20 UTC, tynes commented on packages/watcher/README.md
> +Our `Watcher` allows you to retrieve all transaction hashes related to cross domain messages such as deposits and withdrawals. In order to use, first send a transaction which sends a cross domain mes
There is still a large inferential gap here, ie `In order to use, first send a transaction which sends a cross domain message, for example a deposit from L1 into L2.` isn't technical enough for somebody to just pick up and use. I think specifying `SentMessage(bytes)` event emitted on the xdomain contract would be useful

2020-12-01 21:31 UTC, tynes commented on packages/watcher/src/watcher.ts
> +    // Message was relayed in the past
Will this trigger with more than one if there is a fraud proof that clears the ctc?

2020-12-01 22:19 UTC, kfichter commented on packages/watcher/exec/run-watcher.js
> +			provider: l1Provider,
Tynes starting fights out here

2020-12-08 01:14 UTC, karlfloersch approved these changes
LGTM

2020-12-09 01:41 UTC, tynes requested changes
I think `run-watcher.js` isn't ready yet

2021-01-26 18:35 UTC, tynes approved these changes
I rebased and pushed changes to fix the script, the other changes are less important now

2021-01-26 18:47 UTC, merged